# Generated by Django 3.2 on 2021-04-28 23:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=10, unique=True)),
                ('date_achat', models.DateField()),
                ('garantie_duree', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('achat_lieu', models.CharField(max_length=50)),
                ('achat_prix', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('marque', models.CharField(max_length=80)),
                ('date_derniere_maintenance', models.DateField()),
                ('contrat_maintenance', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')])),
                ('duree', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lieu_affectation', models.CharField(max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('editeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
